### ISSUE TITLE
good suggestion

### ISSUE THREAD

**Issue by hxrofo** [An0nUD4Y/SocialFish#1]
hi
great tool, i like it. i think it would be great if you edit the poll technique to include for example 10 questions, as a quiz or personality test etc... after the victim answers the questions, he is redirected to a new page "quiz completed successfully... please login to facebook to see your results" and then he gets redirected to the login page...after he logs in, he gets the answers...and then is redirected to the real facebook.

**Comment by An0nUD4Y** [comment]
Thank you hxrofo .... for your suggestion.....

**Comment by An0nUD4Y** [comment]
Thanks again...
I like your suggestion......
Just for you and others. I am working on your suggestion....

You will get a update in few days.
