### ISSUE TITLE
Gmail(Google) Outdated Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#100]
Very old Google Mail page.

|Fake|Original|
|-|-|
|![image](https://user-images.githubusercontent.com/35602029/47314839-81995100-d64b-11e8-8de2-dc2ce4cb2b54.png)|![image](https://user-images.githubusercontent.com/35602029/47314863-937af400-d64b-11e8-9f77-1512005d4a93.png)|

**Comment by An0nUD4Y** [comment]
We will update it soon ??

**Comment by sTiKyt** [comment]
@An0nUD4Y but why you closed issue? Maybe someone will fix it xD

**Comment by An0nUD4Y** [comment]
@sTiKyt You can help fixing these pages..?? Maybe??

**Comment by sTiKyt** [comment]
@An0nUD4Y I really want, that why I learn Html and Css right now...

**Comment by usama7628674** [comment]
@sTiKyt Submit a PR.I'll work on it when I have time.

**Comment by sTiKyt** [comment]
@usama7628674 how can i contact with you?

**Comment by usama7628674** [comment]
Why?

**Comment by usama7628674** [comment]
I don't use social media.

**Comment by sTiKyt** [comment]
@usama7628674 i have some questions, there just no place for it :( 
Maybe we can connect using any Linux software?

**Comment by usama7628674** [comment]
What software?

**Comment by sTiKyt** [comment]
@usama7628674 ssh-chat

**Comment by usama7628674** [comment]
yes that would be good

**Comment by sTiKyt** [comment]
I'm closing it because we have #110
