### ISSUE TITLE
LinkedIn Damaged Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#101]
Pure HTML, probably outdated version.

|Fake|Original|
|-|-|
|![image](https://user-images.githubusercontent.com/35602029/47314996-f8364e80-d64b-11e8-902e-299f6724812e.png)|![image](https://user-images.githubusercontent.com/35602029/47315024-0f753c00-d64c-11e8-8029-1b3bce2bfbd3.png)|

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.
