### ISSUE TITLE
Wordpress Outdated Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#103]
I'm not sure about it.

|Fake|Original|
|-|-|
|![image](https://user-images.githubusercontent.com/35602029/47315715-09805a80-d64e-11e8-8baa-6c5bfcb2b7bc.png)|![image](https://user-images.githubusercontent.com/35602029/47315740-1735e000-d64e-11e8-8766-94d4947cc159.png)|

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.
