### ISSUE TITLE
Twitter Damaged Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#104]
Probably outdated, pure HTML.

 |Fake|Original|
|-|-|
| ![image](https://user-images.githubusercontent.com/35602029/47315873-654ae380-d64e-11e8-9b33-bef39e2fe992.png) | ![image](https://user-images.githubusercontent.com/35602029/47315938-8e6b7400-d64e-11e8-971a-cdb49587ac1d.png) |

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.
