### ISSUE TITLE
Snapchat Wrong fonts on page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#105]
Wrong fonts!

|Fake|Original|
|-|-|
|![image](https://user-images.githubusercontent.com/35602029/47316195-3c771e00-d64f-11e8-9d5e-3c2bf3519f73.png)|![image](https://user-images.githubusercontent.com/35602029/47316292-6e888000-d64f-11e8-9f58-c57d34807455.png)|

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.
