### ISSUE TITLE
Yahoo Outdated Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#106]
Now Yahoo don't have Description text, and have one-string login space.

|Fake|Original|
|-|-|
|![image](https://user-images.githubusercontent.com/35602029/47316477-e8b90480-d64f-11e8-8718-d8365027b390.png)|![image](https://user-images.githubusercontent.com/35602029/47316507-f66e8a00-d64f-11e8-822d-39f882763ccf.png)|

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.
