### ISSUE TITLE
Twitch Page Doesn't Exist

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#107]
Now Twitch don't have special login page.

|Fake|Original|
|-|-|
|![image](https://user-images.githubusercontent.com/35602029/47316728-75fc5900-d650-11e8-9008-917776a39947.png)|![image](https://user-images.githubusercontent.com/35602029/47316758-87456580-d650-11e8-8654-6b5d8d865718.png)|

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.

**Comment by An0nUD4Y** [comment]
Thanks For Giving your Time to test all the pages..
