### ISSUE TITLE
Microsoft Outdated Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#108]
Microsoft have new one-string login module.

|Fake|Original|
|-|-|
|![image](https://user-images.githubusercontent.com/35602029/47316912-ef944700-d650-11e8-842e-bee8340bfa38.png)|![image](https://user-images.githubusercontent.com/35602029/47316957-020e8080-d651-11e8-8536-aab83e0df30c.png)|

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.
