### ISSUE TITLE
Create config file for SocialFish

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#113]
Create config file where users will be able to:

- [ ] Change language
- [ ] Set Default answers and add  --noconfirm
- [ ] Something else xD (Will be edited)

**Comment by sTiKyt** [comment]
Assign me to this one please  @An0nUD4Y @usama7628674

**Comment by usama7628674** [comment]
You don't have to raise an issue for a new feature just submit a PR and I'll review it and merge it.

**Comment by sTiKyt** [comment]
@usama7628674 I doing it because wanna have public to do list right here :D

**Comment by usama7628674** [comment]
Okay but you can add this as a description in a PR instead of raising an issue.

**Comment by sTiKyt** [comment]
@usama7628674 know it xD

**Comment by usama7628674** [comment]
Okay I assigned it

**Comment by sTiKyt** [comment]
@usama7628674 what do you think, what properties I must add to config?

**Comment by usama7628674** [comment]
Anything you want.

**Comment by sTiKyt** [comment]
@usama7628674 you don't have any ideas? I just need someone's opinion xD

**Comment by usama7628674** [comment]
Language I guess.

**Comment by usama7628674** [comment]
You mentioned it

**Comment by sTiKyt** [comment]
> You mentioned it

Nothing else?

**Comment by usama7628674** [comment]
I marked the check boxes

**Comment by sTiKyt** [comment]
> I marked the check boxes

Ok, i got it

**Comment by usama7628674** [comment]
Personally I'm out of ideas will get back to you after breakfast.

**Comment by sTiKyt** [comment]
> Personally I'm out of ideas will get back to you after breakfast.

Can we use Telegram app to chat? This very protected and private.

**Comment by usama7628674** [comment]
Yeah

**Comment by sTiKyt** [comment]
> Yeah

ok, write to me, i'm @sTiKyt

**Comment by An0nUD4Y** [comment]
Closing here! @sTiKyt  Please create issues with some labels.!

**Comment by sTiKyt** [comment]
@An0nUD4Y seems like I just can't add labels

**Comment by sTiKyt** [comment]
> Closing here! @sTiKyt Please create issues with some labels.!

I cant add labels..You closed unfinished issue...
