### ISSUE TITLE
ADD NEW SCREENSHOTS ?

### ISSUE THREAD

**Issue by An0nUD4Y** [An0nUD4Y/SocialFish#115]
Hey Guys ? If anyone can help to add new screenshots. 
Create A PR .. I am waiting right there..?

**Comment by sTiKyt** [comment]
@An0nUD4Y OK, just a moment

**Comment by sTiKyt** [comment]
@An0nUD4Y what kind of screenshots do you want to be created?

**Comment by An0nUD4Y** [comment]
@sTiKyt   Thanks for reply

You can add the screeshots same as available here.

& if you can , then please change the youtube video demo link and add a New demo.
I don't have enough time . I hope you will?

**Comment by sTiKyt** [comment]
@An0nUD4Y yep

**Comment by sTiKyt** [comment]
@An0nUD4Y today

**Comment by An0nUD4Y** [comment]
KK

**Comment by sTiKyt** [comment]
@An0nUD4Y I can't understand, why you closing unfixed issues?
