### ISSUE TITLE
There too much of your nickname

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#116]
@An0nUD4Y, can I remove your name from some places in this script?
This just feels terrible when you're working for open source but anywhere nickname of repo creator.
I really wanna help to create best web fishing application, but I don't want to create your brand, @An0nUD4Y
I think people from pentesting repositories never add branded apps like this, maybe this app must have better future, and must be created by Open Source community, not only by you?

I really appreciate your contribution and do not want to offend you. But this not only your project, most work here made by @usama7628674.

Sorry again, I just think about future of this thing.

**Comment by An0nUD4Y** [comment]
@sTiKyt  HAhah You can surely remove them all, I was added them on startup, & never looked again.

So just make it as like you want . After all ITS OPEN SOURCE PROJECT.
