### ISSUE TITLE
about live information

### ISSUE THREAD

**Issue by usama7628674** [An0nUD4Y/SocialFish#13]
The script is showing wrong ip address
[1]IP-ADDRESS = 127.0.0.1   [2]HOSTNAME = localhost

It has to show public ip of victim and the following fields are empty
[5]LATITUDE-LONGITUDE =    [6]ISP =    [7]CITY =    [8]STATE =    [9]COUNTRY =

Also Undefined index and property PHP notice.
Here is the screenshot
![image](https://user-images.githubusercontent.com/29252277/39392925-277466b4-4ad8-11e8-89bb-ff03064b00b4.png)

**Comment by usama7628674** [comment]
> Try to use the generated ngrok link in another device.

Should I try it one same network(LAN) or outside(WAN)?

**Comment by An0nUD4Y** [comment]
Your suggestion works well for me..?
But dude, its working at its best.
I don't think that it should be removed completely.
But if i found any other issues with it, we both will remove it from the upcoming phishing pages.

AND THANK YOU @usama7628674  FOR YOUR GREAT CONTRIBUTION.
