### ISSUE TITLE
Info about yahoo page

### ISSUE THREAD

**Issue by usama7628674** [An0nUD4Y/SocialFish#21]
@An0nUD4Y You have changed index1.html as index.html and deleted previous index.html page.Actually index1.html was mobile page while previous index.html was desktop version.I put a javascrit in desktop page to detect width of victim device and if the victim tries to open ngrok link on mobile he'll get index1.html page and if on desktop pc he'll get index.html page.Now we've only mobile page.Could you please revert those commits?

**Comment by An0nUD4Y** [comment]
@usama7628674  Dear , 

I was tested that desktop version of yahoo page but i found that some of css was not working correctly, And also that the script which redirects a mobile user to yahoo mobile page was not working.
So please Test That Script, If you made them working Then it's Great.
I hope you have understand that why i made change.

Please reply back I am Waiting......

**Comment by usama7628674** [comment]
@An0nUD4Y Ok I'll check it.

**Comment by usama7628674** [comment]
@Just added a PR see [here](https://github.com/An0nUD4Y/SocialFish/pull/26)
