### ISSUE TITLE
What is the difference between WebPages and WebPagesTermux?

### ISSUE THREAD

**Issue by alexmozzhakov** [An0nUD4Y/SocialFish#37]
I cannot understand the difference...

**Comment by usama7628674** [comment]
@alexmozzhakov No difference just for distinguishing.We should delete it and use webpages folder for both termux and linux.

**Comment by alexmozzhakov** [comment]
@usama7628674 nice. I will commit changes soon.

**Comment by alexmozzhakov** [comment]
@usama7628674 should we use a different folder for server root? I don't think so...

**Comment by usama7628674** [comment]
@alexmozzhakov You mean for termux sever or both

**Comment by alexmozzhakov** [comment]
@usama7628674 I mean ServerTermux directory

**Comment by An0nUD4Y** [comment]
Make sure you have tested before making changes...

**Comment by usama7628674** [comment]
@alexmozzhakov Termux version uses arm version of ngrok while linux uses amd64 version.If we don't use
different directory then one version will overwrite the second version and vice versa cuz name is same in both version.

**Comment by usama7628674** [comment]
I think we should leave it as it is now and focus on webpages of termux.

**Comment by usama7628674** [comment]
@alexmozzhakov Yeah it'll be a addition.

**Comment by alexmozzhakov** [comment]
@usama7628674 exactly.

**Comment by usama7628674** [comment]
@alexmozzhakov I'll test the changes you've made in your own repo.

**Comment by usama7628674** [comment]
@alexmozzhakov Submit your commit here so that I'll create server/www folder and make small changes for it to work on both platforms.
