### ISSUE TITLE
Ngrok IP is not shown

### ISSUE THREAD

**Issue by Micrafast** [An0nUD4Y/SocialFish#38]
Have you noticed that you cannot get the real IP while using ngrok? It's always 127.0.0.1

**Comment by alexmozzhakov** [comment]
Whaaat. It's the IP of your web server running locally, the real address is a domain name given by ngrok, not an IP.

**Comment by Micrafast** [comment]
oh, I means the victim's ip is always 127.0.0.1

**Comment by alexmozzhakov** [comment]
Also, he seems to be first to come up with it #13

**Comment by usama7628674** [comment]
But it does not work that way

**Comment by alexmozzhakov** [comment]
Maybe this is due to the way ngrok is set up?

**Comment by usama7628674** [comment]
@alexmozzhakov Ngrok does show public ip after server is started browse to http://127.0.0.1:4040/inspect/http then open ngrok link you'll see ip at top right of page.

**Comment by Micrafast** [comment]
thanks!

**Comment by alexmozzhakov** [comment]
@usama7628674 can't you merge ip.php into base.php or include it so we just pass an IP into the resolver?

**Comment by usama7628674** [comment]
@alexmozzhakov I've included ip.php in base.php but merging isn't working for me

**Comment by alexmozzhakov** [comment]
@usama7628674 I'm sorry, I cannot write code for 2 weeks from now, so it will take some time.

**Comment by usama7628674** [comment]
@alexmozzhakov Don't worry take all the time you need.When you're ready to change it then also make a PR from your repo which is 1 commit ahead of this repo and I'll make some changes which will make it compatible with termux as well.

**Comment by Micrafast** [comment]
I sent a [pull request](https://github.com/An0nUD4Y/SocialFish/pull/39) about this now, @usama7628674 , you can see if it can be merged
