### ISSUE TITLE
traceback error and php error

### ISSUE THREAD

**Issue by sandman4812av** [An0nUD4Y/SocialFish#44]
Hi
when using facebook security alert page
first happened this
Traceback (most recent call last):
  File "SocialFish.py", line 273, in <module>
    waitCreds()
  File "SocialFish.py", line 136, in waitCreds
    with open('Server/www/usernames.txt') as creds:
IOError: [Errno 2] No such file or directory: 'Server/www/usernames.txt'
PHP 7.0.25 Development Server started at Sat Jun  9 11:45:52 2018
Listening on http://127.0.0.1:1111
Document root is /home/aaaa/SocialFish/Server/www
Press Ctrl-C to quit.
==============
and when logging in in the page it does not show creds and takes php error

[Sat Jun  9 11:46:26 2018] 127.0.0.1:45464 [200]: /
[Sat Jun  9 11:46:26 2018] 127.0.0.1:45466 [200]: /style.css
[Sat Jun  9 11:46:26 2018] 127.0.0.1:45468 [200]: /images/logo.png
[Sat Jun  9 11:46:26 2018] 127.0.0.1:45470 [404]: /favicon.ico - No such file or directory
[Sat Jun  9 11:46:26 2018] 127.0.0.1:45472 [200]: /images/fb-ico.png
[Sat Jun  9 11:46:35 2018] PHP Warning:  include(ip.php): failed to open stream: No such file or directory in /home/qapici/SocialFish/Server/www/login.php on line 2
[Sat Jun  9 11:46:35 2018] PHP Warning:  include(): Failed opening 'ip.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /home/aaa/SocialFish/Server/www/login.php on line 2
[Sat Jun  9 11:46:35 2018] PHP Notice:  Undefined index: email in /home/aaaa/SocialFish/Server/www/login.php on line 4
[Sat Jun  9 11:46:35 2018] PHP Notice:  Undefined index: pass in /home/aaaa/SocialFish/Server/www/login.php on line 4

**Comment by sandman4812av** [comment]
and it does not make ngrok subdomain
this doen't work also with fb standart page can't give me creds and instagram gives that error
Traceback (most recent call last):
  File "SocialFish.py", line 273, in <module>
    waitCreds()
  File "SocialFish.py", line 154, in waitCreds
    matchObj = re.match('^(.*?),(.*)$', ipinfo['loc'])
KeyError: 'loc'

did u test this on linux fedora ?

**Comment by An0nUD4Y** [comment]
Hey @sandman4812av  refer to #42

**Comment by usama7628674** [comment]
@An0nUD4Y @sandman4812av I believe it's fixed now try pulling latest commit and rerun the script.
