### ISSUE TITLE
pls advice

### ISSUE THREAD

**Issue by xuserxresu** [An0nUD4Y/SocialFish#49]
Traceback (most recent call last):
  File "SocialFish.py", line 14, in <module>
    from wget import download
ModuleNotFoundError: No module named 'wget'
==========================================
while when i install requirements.txt it says:

Requirement already satisfied: wget==3.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (3.2)

**Comment by usama7628674** [comment]
@xuserxresu We have ported code to python 3 see installation details in readme.md

**Comment by xuserxresu** [comment]
i did install python3.6 and im still getting the same error

**Comment by usama7628674** [comment]
Which commands did you use to install socialfish?List all of them.

**Comment by xuserxresu** [comment]
i used pip instead of pip3.. my bad 
thanks man.. up & running now
