### ISSUE TITLE
Updating repo

### ISSUE THREAD

**Issue by Allespro** [An0nUD4Y/SocialFish#58]
Hi, i have small update, i added vk.com page

**Comment by Allespro** [comment]
how can i send it to you?

**Comment by usama7628674** [comment]
@Allespro Just make a PR or if you don't know about creating PR then make .zip of vk and drag and drop here.I'll upate the repo after then.

**Comment by usama7628674** [comment]
@alexmozzhakov I'll review and merge it in.

**Comment by alexmozzhakov** [comment]
@usama7628674 ty 👍
