### ISSUE TITLE
Traceback when collecting creds

### ISSUE THREAD

**Issue by BasharAG** [An0nUD4Y/SocialFish#59]
The pages work just fine. But the minute creds are submitted, the console shows this error:

Traceback (most recent call last):
  File "SocialFish.py", line 283, in <module>
    waitCreds()
  File "SocialFish.py", line 155, in waitCreds
    ipinfo = json.loads(resp)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by alexmozzhakov** [comment]
can you access `ipinfo.io` from your machine? do you have any proxies/firewall?

**Comment by BasharAG** [comment]
im using an ubuntu cli... i was able to run the original version of SF just fine, but the modified version sends back this error.

**Comment by alexmozzhakov** [comment]
try running `ping google.com` just in case.

**Comment by BasharAG** [comment]
PING google.com (172.217.7.14) 56(84) bytes of data.
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=1 ttl=57 time=2.28 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=2 ttl=57 time=1.46 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=3 ttl=57 time=1.25 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=4 ttl=57 time=1.26 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=5 ttl=57 time=1.28 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=6 ttl=57 time=1.26 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=7 ttl=57 time=1.30 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=8 ttl=57 time=1.25 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=9 ttl=57 time=1.22 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=10 ttl=57 time=1.26 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=11 ttl=57 time=1.31 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=12 ttl=57 time=1.26 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=13 ttl=57 time=1.27 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=14 ttl=57 time=1.28 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=15 ttl=57 time=1.34 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=16 ttl=57 time=1.32 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=17 ttl=57 time=1.28 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=18 ttl=57 time=1.25 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=19 ttl=57 time=1.23 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=20 ttl=57 time=1.30 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=21 ttl=57 time=1.30 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=22 ttl=57 time=1.29 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=23 ttl=57 time=1.24 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=24 ttl=57 time=1.29 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=25 ttl=57 time=1.29 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=26 ttl=57 time=1.31 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=27 ttl=57 time=1.29 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=28 ttl=57 time=1.26 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=29 ttl=57 time=1.30 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=30 ttl=57 time=1.25 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=31 ttl=57 time=1.30 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=32 ttl=57 time=1.28 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=33 ttl=57 time=1.27 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=34 ttl=57 time=1.28 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=35 ttl=57 time=1.24 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=36 ttl=57 time=1.27 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=37 ttl=57 time=1.26 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=38 ttl=57 time=1.27 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=39 ttl=57 time=1.29 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=40 ttl=57 time=1.24 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=41 ttl=57 time=1.28 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=42 ttl=57 time=1.24 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=43 ttl=57 time=1.25 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=44 ttl=57 time=1.25 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=45 ttl=57 time=1.25 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=46 ttl=57 time=1.20 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=47 ttl=57 time=1.29 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=48 ttl=57 time=1.30 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=49 ttl=57 time=1.27 ms
64 bytes from lga25s56-in-f14.1e100.net (172.217.7.14): icmp_seq=50 ttl=57 time=1.27 ms
^C
--- google.com ping statistics ---
50 packets transmitted, 50 received, 0% packet loss, time 49070ms




Seems to be fine, don't you think?

**Comment by alexmozzhakov** [comment]
@BasharAG absolutely. It works on my machine fine, though. Please test [this repo](https://github.com/alexmozzhakov/SocialFish) first. If no success, then please check downloaded file from `wget https://ipinfo.io/json` and if it's ok provide me with your `uname -a`.

**Comment by usama7628674** [comment]
@BasharAG Can't reproduce it tru updating your python to 3.6 and run socialfish as `python3 SocialFish.py`

**Comment by BasharAG** [comment]
@alexmozzhakov The new repo worked. Thank you. Any idea what the issue may have been? Also, when run in tmux, where do the creds get stored?

**Comment by alexmozzhakov** [comment]
@BasharAG sure. There was an issue with decoding charset, I've set up the script to use utf-8 by default if it couldn't be detected. You can see the diff in the [PR](https://github.com/An0nUD4Y/SocialFish/pull/60/files).
