### ISSUE TITLE
add to the list

### ISSUE THREAD

**Issue by ming123245** [An0nUD4Y/SocialFish#61]
please add to the list VK ***vk.com***

**Comment by ming123245** [comment]
and https://www.icloud.com/  for APPLE

**Comment by usama7628674** [comment]
@ming123245 I'll in the upcoming days.Hang tight.

**Comment by ming123245** [comment]
Thank you

**Comment by ming123245** [comment]
I'm really looking forward to VK and icloud

**Comment by An0nUD4Y** [comment]
@ming123245  We will work on that.! Stay Tuned ?

**Comment by usama7628674** [comment]
@ming123245 Added VK in the list of webpages.
