### ISSUE TITLE
unicode encode error

### ISSUE THREAD

**Issue by hxrofo** [An0nUD4Y/SocialFish#65]
hi guys
older versions worked like charm for me on nethunter. today i wanted to git clone the updated version, but when I run python3 SocialFish.py or ./SocialFish.py, it gives me this error. Any fixes? thanks
![36394591_10216836699492743_6322963734054567936_n](https://user-images.githubusercontent.com/17935737/42095911-ddc2d064-7bab-11e8-9dfe-4750ebe8255b.png)

**Comment by alexmozzhakov** [comment]
@hxrofo why not to use termux?
