### ISSUE TITLE
enhancement/improvement

### ISSUE THREAD

**Issue by usama7628674** [An0nUD4Y/SocialFish#66]
@alexmozzhakov I'm thinking about as in the following image
![image](https://user-images.githubusercontent.com/29252277/42121274-edec0a98-7c44-11e8-929f-9a41b32de54c.png)

If the user doesn't fill the required fields we should display an error.What do you say?

**Comment by usama7628674** [comment]
I've applied it on snapchat page and it was working

**Comment by An0nUD4Y** [comment]
Great Idea @usama7628674  This is wht i was waiting for !!! 
Thank You For a great contribution.....

I think you should add it to all the available pages...
As it will make the attack more Dramatic...

**Comment by An0nUD4Y** [comment]
I am Waiting For the improvements....???
