### ISSUE TITLE
google_advanced_web page error

### ISSUE THREAD

**Issue by adaghma** [An0nUD4Y/SocialFish#69]
Hi!
There is a bit of an issue in google_advanced_web page.
When submitting username and password the page redirects to:
http://localhost/login.php
and no data is received at SocialFish terminal.
Also the web page loads very slow at times, any idea why?

Kindly advise
Thanks

**Comment by usama7628674** [comment]
@adaghma Which browser did you use to open the page?

**Comment by usama7628674** [comment]
@adaghma fixed in https://github.com/An0nUD4Y/SocialFish/commit/1b39a019aade2830f9ade27f3eb7b36e8f212e3c
