### ISSUE TITLE
not install 

### ISSUE THREAD

**Issue by shivgori** [An0nUD4Y/SocialFish#73]
1) when i type python SocialFish.py then i got error
Traceback (most recent call last):
  File "SocialFish.py", line 12, in <module>
    from urllib.request import urlopen, quote, unquote
ImportError: No module named request
2) when i type sudo apt install python3-pip i got error
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pip

**Comment by usama7628674** [comment]
@alexmozzhakov Either your sources.list is messed up or you didn't do `apt update`.
