### ISSUE TITLE
Add both Servers Ngrok/Serveo As choice .....

### ISSUE THREAD

**Issue by An0nUD4Y** [An0nUD4Y/SocialFish#76]
@usama7628674 @alexmozzhakov Guys you Don't think that we Should add Both Of the servers in case if one of them doesn't work . When i was tested the updated script it took me a lot to feel it...
But even after that for me it doesn't working as it should..? #74 #75

**Comment by An0nUD4Y** [comment]
I am thinking something like this ...
[https://github.com/thelinuxchoice/shellphish/blob/master/shellphish.sh](https://github.com/thelinuxchoice/shellphish/blob/master/shellphish.sh)

**Comment by alexmozzhakov** [comment]
@An0nUD4Y Yeah, I saw it in my discovery, but having 2 versions can confuse and may cause difficulties with maintaining termux. Sometimes it's forgotten to be updated and idk may confuse someone

**Comment by usama7628674** [comment]
@An0nUD4Y @alexmozzhakov I can work on it and add both serveo and ngrok and make it compatible with termux as well.

**Comment by alexmozzhakov** [comment]
@usama7628674 @An0nUD4Y the question is if we actually need both if serveo will work on termux. The main advantage of not having ngrok is not having to download binaries (except ssh in rare cases) and also the advantage of not having to maintain 2 almost the same files.

**Comment by usama7628674** [comment]
@alexmozzhakov We can use two at the same time and using just one file to maintain it on termux and linux.

**Comment by usama7628674** [comment]
@alexmozzhakov Who said seveo isn't working in termux?

**Comment by alexmozzhakov** [comment]
@usama7628674 [An0nUD4Y did](https://github.com/An0nUD4Y/SocialFish/pull/75#issuecomment-408611061)

**Comment by usama7628674** [comment]
@An0nUD4Y It's working as it should.
