### ISSUE TITLE
Add an option to choose a desirable serveo link....

### ISSUE THREAD

**Issue by An0nUD4Y** [An0nUD4Y/SocialFish#78]
@alexmozzhakov @usama7628674 @Micrafast  We should add an option in serveo ...
By which anyone can choose a link according to him...
[Read These Features](http://serveo.net)

**Comment by usama7628674** [comment]
@alexmozzhakov You are right custom link only change starting words of link rest will remain the same like
*.serveo.net

**Comment by usama7628674** [comment]
And serveo doesn't generate same link again and again.

**Comment by usama7628674** [comment]
This will not improve anything related to this tool.Closing now

**Comment by alexmozzhakov** [comment]
@usama7628674 "starting words of link" is called subdomain. And you can generate "same link" again and again, thats the point of manually selecting it. I was asking @An0nUD4Y, and I'm still waiting for his response.

**Comment by An0nUD4Y** [comment]
@alexmozzhakov @usama7628674 Adding a custom subdomain in link will make that link trustful...
& And it helps a lot in Social-Engineering... Whenever i got some time i will try it..???
