### ISSUE TITLE
Ngrok URL is empty

### ISSUE THREAD

**Issue by shan0501** [An0nUD4Y/SocialFish#80]
after selecting Ngrok as the option, 

Ngrok URL : (empty)

**Comment by usama7628674** [comment]
@shan0501 Go to Server folder and execute `./ngrok http 80` to see if ngrok is working properly.

**Comment by shan0501** [comment]
@usama7628674 i'm using kali linux, I'm facing same issue in Serveo also.

**Comment by usama7628674** [comment]
@shan0501 Did you execute the command that I wrote above?

**Comment by usama7628674** [comment]
@shan0501 reclone and try again.
