### ISSUE TITLE
Site is Black

### ISSUE THREAD

**Issue by steve01101** [An0nUD4Y/SocialFish#82]
A victim opened the site and saw everything black, but if I open it I can see it well

**Comment by alexmozzhakov** [comment]
Which one? What victim 👀?

**Comment by steve01101** [comment]
Instagram's site but now it's ok, I don't know why.

**Comment by usama7628674** [comment]
@steve01101 It does happen with serveo try ngrok.

**Comment by mcsariyandi** [comment]
ngrok.url is not visible.
Why.?

**Comment by steve01101** [comment]
Usama I used ngrok

**Comment by usama7628674** [comment]
But you said "now it's okay".
