### ISSUE TITLE
Ngrok URL blank

### ISSUE THREAD

**Issue by mcsariyandi** [An0nUD4Y/SocialFish#83]
Ngrok URL and serveo blank, why.?

**Comment by usama7628674** [comment]
@mcsariyandi It maybe a networking issue.Check your connection.

**Comment by mcsariyandi** [comment]
the problem has been resolved ... it turns out I have to use a VPN 😅

**Comment by HAKRSINGH** [comment]
Why a VPN?

**Comment by usama7628674** [comment]
You don't need vpn

**Comment by Dipraj** [comment]
as we know now ngrok required authtoken... i also provide my authtoken to ngrok itself.. but it still black. it's request to the developer try to fix it as soon as posssible
