### ISSUE TITLE
is it possible to see the saved passwords?

### ISSUE THREAD

**Issue by steve01101** [An0nUD4Y/SocialFish#84]
hi. I closed the terminal before seeing the password, can I see it in another way?

**Comment by Micrafast** [comment]
As I know it's impossible now hmmmm....... in fact if you close the terminal, the victim will be not able to see your fishing page

**Comment by steve01101** [comment]
sure? does not a way exist?

**Comment by Micrafast** [comment]
no way exist but.... I made a pull request to prevent this again #86
