### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by darkmidus** [An0nUD4Y/SocialFish#87]
I attempt to put in the command sudo apt install python3-pip
and it gives me the error
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python3-pip

**Comment by usama7628674** [comment]
@darkmidus Do `apt update` then `apt install python3-pip`

**Comment by darkmidus** [comment]
I have done what you have told me but i still get the same error

**Comment by usama7628674** [comment]
@darkmidus Can you share sources.list file?

**Comment by darkmidus** [comment]
Sure

# 

# deb cdrom:[Debian GNU/Linux 2017.3 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20171109-13:49]/ kali-rolling contrib main non-free

#deb cdrom:[Debian GNU/Linux 2017.3 _Kali-rolling_ - Official Snapshot amd64 LIVE/INSTALL Binary 20171109-13:49]/ kali-rolling contrib main non-free

**Comment by usama7628674** [comment]
@darkmidus Open your sources.list file and remove everything then paste the following
```
deb https://http.kali.org/kali kali-rolling main non-free contrib
# For source package access, uncomment the following line
# deb-src http://http.kali.org/kali kali-rolling main non-free contrib

```

**Comment by usama7628674** [comment]
Save it then do `apt update`

**Comment by darkmidus** [comment]
Doing apt update gives me this error now

root@kali:~# apt update
Get:1 https://archive-7.kali.org/kali kali-rolling InRelease [30.5 kB]
Err:1 https://archive-7.kali.org/kali kali-rolling InRelease
  The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
Reading package lists... Done
W: GPG error: https://archive-7.kali.org/kali kali-rolling InRelease: The following signatures were invalid: EXPKEYSIG ED444FF07D8D0BF6 Kali Linux Repository <devel@kali.org>
E: The repository 'https://http.kali.org/kali kali-rolling InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by usama7628674** [comment]
execute the following in terminal
```
apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 7D8D0BF6
```

**Comment by darkmidus** [comment]
python3-pip is installing now, thanks for all your help

**Comment by usama7628674** [comment]
No problem.

**Comment by tokiijnr** [comment]
pls how do i fix this:

root@kali:~# sudo apt install python3-pip 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpython3.7-stdlib : Breaks: python3-distutils (< 3.6.5~rc1-2) but 3.6.4-2 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by tokiijnr** [comment]
@usama7628674

**Comment by usama7628674** [comment]
@tokiijnr Do `apt install --reinstall libpython3.7-stdlib` or `apt install libpython3.7-stdlib` then `apt install --reinstall python3-distutils` or `apt install python3-distutils`

**Comment by tokiijnr** [comment]
@usama7628674
thanks so much
