### ISSUE TITLE
SERVEO URL

### ISSUE THREAD

**Issue by lordcharlx** [An0nUD4Y/SocialFish#88]
the serveo url is not stable ... at times it shows sometimes it doesn't  and most times it shows it doesn't work

**Comment by usama7628674** [comment]
I'll look into it later.

**Comment by usama7628674** [comment]
@lordcharlx Reclone it cuz I can't reproduce it.

**Comment by lordcharlx** [comment]
correct .... now blazing hot    7 bottles of beer for you
