### ISSUE TITLE
Serveo link issue 

### ISSUE THREAD

**Issue by atroxGhost** [An0nUD4Y/SocialFish#89]
Some Serveo links doesn't load in browser termux

**Comment by usama7628674** [comment]
@atroxGhost You mean only white page after serveo link loads.

**Comment by usama7628674** [comment]
If it is then it's only a problem of serveo cuz it does occur to me sometimes.

**Comment by usama7628674** [comment]
make sure you're updated to latest commit and if this happens again then just rerun socialfish.

**Comment by atroxGhost** [comment]
Everything is updated on the fifth attempt it worked hopefully it's just a today issue and if it isn't let's hope it can get fixed :/

**Comment by usama7628674** [comment]
@atroxGhost You could use ngrok if seveo does not work.
