### ISSUE TITLE
How to redirect

### ISSUE THREAD

**Issue by darkmidus** [An0nUD4Y/SocialFish#91]
I am using termux, and I was wondering if it was possible to make the login page redirect after submit was clicked.

**Comment by usama7628674** [comment]
@darkmidus It'll redirect to original site.

**Comment by darkmidus** [comment]
I know, but could I get it to redirect to something I wanted.

**Comment by usama7628674** [comment]
@darkmidus You can change header location in login.php of the phishing page you want to use.For example navigate to webpages/snapchat_web directory then change header location in login.php file.

**Comment by darkmidus** [comment]
I knew that, but I'm on termux (Android) and you can't really get to that folder.

**Comment by usama7628674** [comment]
@darkmidus okay I may add this when I've time.
