### ISSUE TITLE
Ngrok URL not showing up termux

### ISSUE THREAD

**Issue by darkmidus** [An0nUD4Y/SocialFish#93]
On termux, when you choose ngrok, nothing happens. That's why I have been using Serveo.

**Comment by usama7628674** [comment]
Well it's working fine on my side.

**Comment by darkmidus** [comment]
When I choose ngrok nothing happens, is it possible to send pictures on GitHub

**Comment by usama7628674** [comment]
Just drag and drop pictures in this section.

**Comment by darkmidus** [comment]
![screenshot_20181017-213611](https://user-images.githubusercontent.com/39868305/47127906-b7f25d00-d254-11e8-99ad-a47ea377a49d.png)

**Comment by darkmidus** [comment]
It just does this, nothing happens. Serveo works perfectly, but Ngrok dosen't.

**Comment by usama7628674** [comment]
Run ngrok manually and post the pic here.Navigate to Server/www and run `ngrok http 80`

**Comment by An0nUD4Y** [comment]
I think issue has been solved ... I AM CLOSING....!
