### ISSUE TITLE
Steam Bad Quality

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#95]
- [ ] Add Steam Guard when Login:Pass complete.
- [ ] Fix text:

| FAKE  | ORIGINAL |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/35602029/47312041-f23c6f80-d643-11e8-8859-75302a8b23e1.png)  | ![image](https://user-images.githubusercontent.com/35602029/47312083-0f713e00-d644-11e8-9171-120c8878aa15.png) |

**Comment by An0nUD4Y** [comment]
Its looking Perfect... But still We will update all our pages..?
Stay Tuned..?

**Comment by sTiKyt** [comment]
@An0nUD4Y cause of this I started to learn Html & Css xD
