### ISSUE TITLE
Tested on Arch Linux

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#96]
My system:
Platform: linux x86_64
Distribution: Arch Linux
Kernel Release: 4.18.14-arch1-1-ARCH
CPU Model: Intel(R) Core(TM) i3-7100U CPU
CPU Core: 4
CPU Speed: 2.40GHz
RAM: 4GB

Tested:
VK - blank page.
Instagram - all right.
Steam - all right.

**Comment by An0nUD4Y** [comment]
Thanks for testing the SocialFish. You can contribute with us. To make SocialFish more advanced.
