### ISSUE TITLE
Instagram Outdated Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#98]
| Fake | Original |
| ----- | ----- |
| ![image](https://user-images.githubusercontent.com/35602029/47313375-79d7ad80-d647-11e8-9461-3e08e896eae6.png) | ![image](https://user-images.githubusercontent.com/35602029/47313420-94aa2200-d647-11e8-9d10-c99fcf2d2f67.png) |

**Comment by An0nUD4Y** [comment]
i think some of the files are not correctly loading..?
Please try to reload those pages And provide another screenshot..?

**Comment by sTiKyt** [comment]
@An0nUD4Y I tried already, on some devices
