### ISSUE TITLE
Facebook Damaged Page

### ISSUE THREAD

**Issue by sTiKyt** [An0nUD4Y/SocialFish#99]
Pure HTML, probably outdated version.

| Fake | Original |
| --------------- | ---------------|
| ![image](https://user-images.githubusercontent.com/35602029/47314601-ca9cd580-d64a-11e8-8265-f8f46ad102cd.png) | ![image](https://user-images.githubusercontent.com/35602029/47314637-e56f4a00-d64a-11e8-8ca5-01bbf4463c46.png) |

**Comment by An0nUD4Y** [comment]
Ok we will shortly Provide An updated Version of all Webpages.
STAY TUNED.
or
You can contribute.
